language: ruby
sudo: false
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head

gemfile:
  - gemfiles/Gemfile-rails4.1.x
  - gemfiles/Gemfile-rails4.2.x
  - gemfiles/Gemfile-rails5.0.x
  - gemfiles/Gemfile-rails5.1.x
  - gemfiles/Gemfile-rails_edge

matrix:
  allow_failures:
    - rvm: 2.2.9
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.3.6
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.4.3
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails4.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails_edge
